// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prefer the direct (non-pooled) connection for CLI operations like
    // `db push`; pooled connections can fail on DDL/prepared statements.
    url: process.env["POSTGRES_URL_NON_POOLING"] || process.env["DATABASE_URL"],
  },
});
