/**
 * Provision (or refresh) a non-production database for the test suites.
 *
 *   npx tsx --env-file=.env scripts/provision-test-db.ts
 *
 * Creates <live database>_test on the same server, applies the current Prisma
 * schema, and writes .env.test pointing at it. Suites then run with
 * --env-file=.env.test and can never touch live records.
 *
 * Why this exists: the app's own .env points at the production database, so
 * every suite that created a fixture was writing to live data.
 */
import { execFileSync } from "node:child_process";
import { writeFileSync, existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { Client } from "pg";
import { connectionString, describeTarget } from "./lib/dump";

function withDatabase(url: string, dbName: string): string {
  const u = new URL(url);
  u.pathname = `/${dbName}`;
  return u.toString();
}

void (async () => {
  const live = connectionString();
  const liveDb = new URL(live).pathname.replace(/^\//, "");
  const testDb = `${liveDb}_test`;
  const testUrl = withDatabase(live, testDb);

  console.log(`Live:  ${describeTarget(live)}`);
  console.log(`Test:  ${describeTarget(testUrl)}`);
  if (testDb === liveDb) throw new Error("Refusing to proceed: test and live database names match.");

  const admin = new Client({ connectionString: withDatabase(live, "postgres") });
  admin.on("error", (e) => console.error(`  [admin] ${e.message}`));
  await admin.connect();
  try {
    const exists = await admin.query<{ n: string }>(
      "SELECT count(*)::text AS n FROM pg_database WHERE datname = $1",
      [testDb],
    );
    if (exists.rows[0].n === "0") {
      await admin.query(`CREATE DATABASE "${testDb}"`);
      console.log(`  created ${testDb}`);
    } else {
      console.log(`  ${testDb} already exists`);
    }
  } finally {
    await admin.end();
  }

  console.log("  applying the current schema");
  // Every url variable, or prisma.config.ts's preference for
  // POSTGRES_URL_NON_POOLING would push this at production instead.
  execFileSync(
    process.execPath,
    [resolve("node_modules/prisma/build/index.js"), "db", "push", "--accept-data-loss"],
    {
      env: {
        ...process.env,
        DATABASE_URL: testUrl,
        POSTGRES_URL_NON_POOLING: testUrl,
        DATABASE_URL_UNPOOLED: testUrl,
      },
      stdio: "pipe",
    },
  );

  const envPath = resolve(".env.test");
  const body =
    `# Test database, generated by scripts/provision-test-db.ts.\n` +
    `# Run suites with: npx tsx --env-file=.env.test <script>\n` +
    `# Never point this at the production database.\n` +
    `DATABASE_URL="${testUrl}"\n` +
    `DATABASE_URL_UNPOOLED="${testUrl}"\n` +
    `POSTGRES_URL_NON_POOLING="${testUrl}"\n`;
  if (existsSync(envPath) && readFileSync(envPath, "utf8") === body) {
    console.log("  .env.test already current");
  } else {
    writeFileSync(envPath, body, "utf8");
    console.log("  wrote .env.test");
  }

  const t = new Client({ connectionString: testUrl });
  t.on("error", (e) => console.error(`  [test] ${e.message}`));
  await t.connect();
  const tables = await t.query<{ n: string }>(
    "SELECT count(*)::text AS n FROM pg_tables WHERE schemaname = 'public'",
  );
  await t.end();
  console.log(`OK  ${testDb} ready with ${tables.rows[0].n} tables.`);
  console.log("    Seed it if suites need reference data: npx tsx --env-file=.env.test prisma/seed.ts");
})();
