/**
 * House style checks that are cheap to state and easy to forget.
 *
 *   npx tsx scripts/test-style.ts
 *
 * Two rules.
 *
 * NO EM DASHES. The character reads as machine-written, and asking for it to be
 * removed by hand has not made it stop coming back, so it is a build failure
 * now instead of a preference.
 *
 * NO <Card> WITHOUT PADDING. The Card component deliberately supplies no
 * padding of its own, so every screen passes one. When a screen forgets, its
 * content sits flush against the card border and the page looks broken while
 * every individual class on it is correct, which makes it hard to see in review
 * and easy to ship. The covers screen shipped that way: seven cards, none of
 * them padded, on the one page out of a hundred and eighteen usages that did
 * not follow the convention.
 *
 * An en dash (U+2013) is a different character and is allowed: src/lib/format.ts
 * uses one for the "no value" glyph in tables, and booking-core.ts joins a
 * booking window with one.
 *
 * This file builds the banned character from its code point rather than writing
 * it, so the checker does not trip over itself.
 */
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";

const EM_DASH = String.fromCodePoint(0x2014);

/** Paths the rule does not apply to, with the reason. */
const EXEMPT: { prefix: string; why: string }[] = [
  { prefix: "src/generated/", why: "generated by prisma, not written here" },
  { prefix: "package-lock.json", why: "generated by npm" },
];

function tracked(): string[] {
  return execFileSync("git", ["ls-files"], { encoding: "utf8" })
    .split("\n")
    .map((l) => l.trim())
    .filter(Boolean);
}

const files = tracked().filter((f) => !EXEMPT.some((e) => f.startsWith(e.prefix)));

let hits = 0;
const offenders: { file: string; line: number; text: string }[] = [];

for (const file of files) {
  let text: string;
  try {
    text = readFileSync(file, "utf8");
  } catch {
    continue; // a deleted-but-tracked path, or a binary we cannot read
  }
  if (!text.includes(EM_DASH)) continue;
  for (const [i, line] of text.split("\n").entries()) {
    if (!line.includes(EM_DASH)) continue;
    hits += [...line].filter((c) => c === EM_DASH).length;
    offenders.push({ file, line: i + 1, text: line.trim() });
  }
}

console.log(`Checked ${files.length} tracked files for em dashes.\n`);

/* ---------- Rule 2: a Card must be given padding ---------- */

/**
 * A card has to say something about its own interior. Three ways to say it:
 *
 *   a padding utility          the card pads its content itself (`p-5` here)
 *   `divide-*`                 a list whose rows carry their own padding
 *   `overflow-hidden`          full bleed, children run to the border on purpose
 *
 * `p-0` counts as padding: it is an explicit "none", which is what a card
 * wrapping a full-width table wants.
 *
 * What this catches is a card that expresses NO interior intent at all, which
 * is the shape the bug took: `<Card>` bare, or `<Card className="mb-6">` where
 * the only class is an outside margin. Margins are deliberately not accepted as
 * intent, because saying where a card sits on the page says nothing about what
 * happens inside it.
 */
const INTERIOR = /\b((p|px|py|pt|pb|pl|pr)-\d|divide-|overflow-hidden)/;

const unpadded: { file: string; line: number; text: string }[] = [];

for (const file of files.filter((f) => f.endsWith(".tsx"))) {
  let text: string;
  try {
    text = readFileSync(file, "utf8");
  } catch {
    continue;
  }
  if (!text.includes("<Card")) continue;
  for (const [i, line] of text.split("\n").entries()) {
    // Opening tags only, and only ones written on a single line. A Card whose
    // props are spread over several lines is checked by the className search
    // below instead of being reported as a false positive.
    const m = line.match(/<Card(\s[^>]*)?>/);
    if (!m) continue;
    const props = m[1] ?? "";
    if (INTERIOR.test(props)) continue;
    // className={...} is a computed value this cannot read; leave it alone.
    if (/className=\{/.test(props)) continue;
    unpadded.push({ file, line: i + 1, text: line.trim() });
  }
}

console.log(`Checked ${files.filter((f) => f.endsWith(".tsx")).length} components for cards with no interior layout.\n`);

if (unpadded.length) {
  for (const o of unpadded.slice(0, 40)) {
    console.log(`  ${o.file}:${o.line}`);
    console.log(`    ${o.text.slice(0, 110)}`);
  }
  console.log(
    `\nFAILED: ${unpadded.length} <Card> with no padding class.`,
  );
  console.log("Card supplies none of its own, so content sits flush against the border.");
  console.log("Add the house padding, `p-5`. If the card is meant to run full bleed,");
  console.log("say so with `divide-y`, `overflow-hidden`, or an explicit `p-0`.");
  process.exit(1);
}

if (offenders.length) {
  for (const o of offenders.slice(0, 60)) {
    // Mark the position so the character is findable in an editor.
    console.log(`  ${o.file}:${o.line}`);
    console.log(`    ${o.text.slice(0, 110)}`);
  }
  if (offenders.length > 60) console.log(`  ... and ${offenders.length - 60} more lines`);
  console.log(
    `\nFAILED: ${hits} em dash${hits === 1 ? "" : "es"} on ${offenders.length} line${
      offenders.length === 1 ? "" : "s"
    }.`,
  );
  console.log("Reword rather than deleting the character: a colon, a semicolon, a comma,");
  console.log("a pair of brackets, or two shorter sentences. An en dash is fine.");
  process.exit(1);
}

console.log("Exempt, with the reason:");
for (const e of EXEMPT) console.log(`  ${e.prefix}\n    ${e.why}`);
console.log("\nCLEAN: no em dashes in tracked files, and every card is padded.");
