/**
 * House style checks that are cheap to state and easy to forget.
 *
 *   npx tsx scripts/test-style.ts
 *
 * Currently one rule: no em dashes. The character reads as machine-written, and
 * asking for it to be removed by hand has not made it stop coming back, so it is
 * a build failure now instead of a preference.
 *
 * An en dash (U+2013) is a different character and is allowed: src/lib/format.ts
 * uses one for the "no value" glyph in tables, and booking-core.ts joins a
 * booking window with one.
 *
 * This file builds the banned character from its code point rather than writing
 * it, so the checker does not trip over itself.
 */
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";

const EM_DASH = String.fromCodePoint(0x2014);

/** Paths the rule does not apply to, with the reason. */
const EXEMPT: { prefix: string; why: string }[] = [
  { prefix: "src/generated/", why: "generated by prisma, not written here" },
  { prefix: "package-lock.json", why: "generated by npm" },
];

function tracked(): string[] {
  return execFileSync("git", ["ls-files"], { encoding: "utf8" })
    .split("\n")
    .map((l) => l.trim())
    .filter(Boolean);
}

const files = tracked().filter((f) => !EXEMPT.some((e) => f.startsWith(e.prefix)));

let hits = 0;
const offenders: { file: string; line: number; text: string }[] = [];

for (const file of files) {
  let text: string;
  try {
    text = readFileSync(file, "utf8");
  } catch {
    continue; // a deleted-but-tracked path, or a binary we cannot read
  }
  if (!text.includes(EM_DASH)) continue;
  for (const [i, line] of text.split("\n").entries()) {
    if (!line.includes(EM_DASH)) continue;
    hits += [...line].filter((c) => c === EM_DASH).length;
    offenders.push({ file, line: i + 1, text: line.trim() });
  }
}

console.log(`Checked ${files.length} tracked files for em dashes.\n`);

if (offenders.length) {
  for (const o of offenders.slice(0, 60)) {
    // Mark the position so the character is findable in an editor.
    console.log(`  ${o.file}:${o.line}`);
    console.log(`    ${o.text.slice(0, 110)}`);
  }
  if (offenders.length > 60) console.log(`  ... and ${offenders.length - 60} more lines`);
  console.log(
    `\nFAILED: ${hits} em dash${hits === 1 ? "" : "es"} on ${offenders.length} line${
      offenders.length === 1 ? "" : "s"
    }.`,
  );
  console.log("Reword rather than deleting the character: a colon, a semicolon, a comma,");
  console.log("a pair of brackets, or two shorter sentences. An en dash is fine.");
  process.exit(1);
}

console.log("Exempt, with the reason:");
for (const e of EXEMPT) console.log(`  ${e.prefix}\n    ${e.why}`);
console.log("\nCLEAN: no em dashes in tracked files.");
